Module majeur : Utiliser un framework en backend. x
Module mineur : Utiliser une base de données en backend. x
Module majeur : Gestion utilisateur standard, authentification, utilisateurs
en tournois. x
Module majeur : Implémenter une authentification à distance. x
Module majeur : Joueurs à distance x
Module majeur : Multijoueurs (plus de 2 dans la même partie)
Module majeur : Clavardage en direct (live chat).
Module majeur : Implémenter un adversaire contrôlé par IA. x
Module mineur : Panneaux d’affichage (dashboards) d’utilisateurs et statistiques des parties. x
Module mineur : Étendre la compatibilité des navigateurs web.

https://api.intra.42.fr/oauth/authorize?client_id=u-s4t2ud-4bc482d21834a4addd9108c8db4a5f99efb73b172f1a4cb387311ee09a26173c&redirect_uri=https%3A%2F%2F10.14.11.3%3A8443%2Fcheck_authorize%2F&response_type=code

XSS dans la description du profil - check avec <img src=x onerror=alert(1)> <script>alert(1);</script>

Erreur 500

AttributeError: 'NoneType' object has no attribute 'position'
User with id None does not exist
Internal Server Error: /api/get_user/ezanotti
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/web/mainApp/views/api.py", line 326, in get_user
    if (scores.first().position == 1):
        ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'position'

Utiliser uuidv4 au lieu de uuidv1

Valider email avec https://stackoverflow.com/a/19222468 dans usersView.py
Utiliser urlencode https://stackoverflow.com/a/67217978 plutot que de le fqire a la main
possible de faire des templates pour les emails

Verifier qu'on peut pas passer null dans un password

Internal Server Error: /profile/elias
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/web/mainApp/views/usersView.py", line 392, in profile
    if not len(new_password):
           ^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

web-1       | ERROR:    Exception in ASGI application
web-1       | Traceback (most recent call last):
web-1       |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 255, in run_asgi
web-1       |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
web-1       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1       |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
web-1       |     return await self.app(scope, receive, send)
web-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nginx-1     | 172.26.0.1 - - [03/Apr/2024:12:04:53 +0000] "GET /ws/chat// HTTP/1.1" 500 21 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36" "-"
web-1       |   File "/usr/local/lib/python3.11/site-packages/channels/routing.py", line 62, in __call__
web-1       |     return await application(scope, receive, send)
web-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1       |   File "/usr/local/lib/python3.11/site-packages/channels/sessions.py", line 47, in __call__
web-1       |     return await self.inner(dict(scope, cookies=cookies), receive, send)
web-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1       |   File "/usr/local/lib/python3.11/site-packages/channels/sessions.py", line 263, in __call__
web-1       |     return await self.inner(wrapper.scope, receive, wrapper.send)
web-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1       |   File "/usr/local/lib/python3.11/site-packages/channels/auth.py", line 185, in __call__
web-1       |     return await super().__call__(scope, receive, send)
web-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1       |   File "/usr/local/lib/python3.11/site-packages/channels/middleware.py", line 24, in __call__
web-1       |     return await self.inner(scope, receive, send)
web-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1       |   File "/usr/local/lib/python3.11/site-packages/channels/routing.py", line 134, in __call__
web-1       |     raise ValueError("No route found for path %r." % path)
web-1       | ValueError: No route found for path 'ws/chat//'.

>>>>>>>>>> 1st to join



web-1       | ERROR:    Exception in ASGI application
web-1       | Traceback (most recent call last):
web-1       |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 255, in run_asgi
web-1       |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
web-1       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1       |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
web-1       |     return await self.app(scope, receive, send)
web-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1       |   File "/usr/local/lib/python3.11/site-packages/channels/routing.py", line 62, in __call__
web-1       |     return await application(scope, receive, send)
web-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1       |   File "/usr/local/lib/python3.11/site-packages/channels/sessions.py", line 47, in __call__
web-1       |     return await self.inner(dict(scope, cookies=cookies), receive, send)
web-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1       |   File "/usr/local/lib/python3.11/site-packages/channels/sessions.py", line 263, in __call__
web-1       |     return await self.inner(wrapper.scope, receive, wrapper.send)
web-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1       |   File "/usr/local/lib/python3.11/site-packages/channels/auth.py", line 185, in __call__
web-1       |     return await super().__call__(scope, receive, send)
web-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1       |   File "/usr/local/lib/python3.11/site-packages/channels/middleware.py", line 24, in __call__
web-1       |     return await self.inner(scope, receive, send)
web-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1       |   File "/usr/local/lib/python3.11/site-packages/channels/routing.py", line 116, in __call__
web-1       |     return await application(
web-1       |            ^^^^^^^^^^^^^^^^^^
web-1       |   File "/usr/local/lib/python3.11/site-packages/channels/consumer.py", line 94, in app
web-1       |     return await consumer(scope, receive, send)
web-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1       |   File "/usr/local/lib/python3.11/site-packages/channels/consumer.py", line 58, in __call__
web-1       |     await await_many_dispatch(
web-1       |   File "/usr/local/lib/python3.11/site-packages/channels/utils.py", line 50, in await_many_dispatch
web-1       |     await dispatch(result)
web-1       |   File "/usr/local/lib/python3.11/site-packages/channels/consumer.py", line 73, in dispatch
web-1       |     await handler(message)
web-1       |   File "/usr/local/lib/python3.11/site-packages/channels/generic/websocket.py", line 194, in websocket_receive
web-1       |     await self.receive(text_data=message["text"])
web-1       |   File "/home/app/web/mainApp/consumers/gameConsumer.py", line 39, in receive
web-1       |     gameSettings = self.gameSettingsInstances[gameID]
web-1       |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
web-1       | KeyError: '13'
web-1       | INFO:     connection closed
web-1       | INFO:     172.27.0.5:52152 - "GET /api/get_game_info HTTP/1.0" 200 OK


>>>>>>>>>>>>> start moving before canva load


3 in tournament -> ai game the tournament 